FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:1.24

LABEL org.opencontainers.image.licenses="GPL-3.0-or-later"
LABEL org.opencontainers.image.description="SWIM DNOTAM Provider - A service that receives DNOTAM (Digital NOTAM) events via Kafka, filters them according to active subscriptions, and distributes them via AMQP to interested consumers. Implements the SWIM-TI Yellow Profile Publish/Subscribe pattern for real-time aeronautical notifications."
LABEL org.opencontainers.image.source="https://github.com/swim-developer/swim-digital-notam-provider"
LABEL org.opencontainers.image.version="0.0.1"

ENV LANGUAGE='en_US:en'

COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 target/quarkus-app/*.jar /deployments/
COPY --chown=185 target/quarkus-app/app/ /deployments/app/
COPY --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
EXPOSE 8443
EXPOSE 9000
EXPOSE 9080
USER 185
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]
