apiVersion: v1
kind: Secret
metadata:
  name: swim-dnotam-provider-secret
  namespace: swim-demo
  labels:
    app: swim-dnotam-provider
    component: credentials
    app.kubernetes.io/part-of: swim-dnotam
type: Opaque
stringData:
  POSTGRES_USER: swim-provider
  POSTGRES_PASSWORD: swim-provider
  
  AMQP_USERNAME: admin
  AMQP_PASSWORD: admin

