apiVersion: v1
kind: Secret
metadata:
  name: swim-dnotam-provider-oidc-secret
  namespace: swim-demo
  labels:
    app: swim-dnotam-provider
    app.kubernetes.io/part-of: swim-dnotam
type: Opaque
stringData:
  OIDC_ENABLED: "true"
  OIDC_AUTH_SERVER_URL: "https://rhbk.apps.ocp4.masales.cloud/realms/swim"
  OIDC_CLIENT_ID: "swim-dnotam-provider"
  OIDC_CLIENT_SECRET: "L3wFbBGpRtHzfkLj0ntMB7Q9DQx8Idvc"

