apiVersion: v1
kind: ConfigMap
metadata:
  name: swim-dnotam-provider-topics
  namespace: swim-demo
  labels:
    app: swim-dnotam-provider
    app.kubernetes.io/part-of: swim-dnotam
data:
  DNOTAM_TOPICS_CONFIG: '["RWY.CLS","TWY.CLS","STAND.STS","OBS.NEW","NAV.UNS","SAA.ACT"]'
